501-c-Free/front_end_501cFree

- .circleci/config.yml
- db/schema.rb
> Try a different approach for circle ci, no plans to merge unless it passes on circle ci

- Gemfile.lock
- app/controllers/developers_controller.rb
- app/poros/developer.rb
- app/services/developer_service.rb
- app/views/developers/new.html.erb
- config/puma.rb
- config/routes.rb
- spec/features/dev/new_spec.rb
- spec/poros/developer_spec.rb
- spec/services/developer_service_spec.rb
- [ x ] Commit messages clearly note what has been updated
- [ x ] Tests are thorough (include Model tests where necessary) and are passing
- skipped feature testing until we have a working BE
Cannot see it on local host yet
Need to work through how to send requests to the front end to create or fetch our users. Will work on getting that up and running by EOD Saturday
> Cb user create

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/controllers/developers_controller.rb
- app/controllers/non_profits_controller.rb
- app/controllers/sessions_controller.rb
- app/services/developer_service.rb
- app/services/session_service.rb
- app/views/developers/new.html.erb
- config/routes.rb
- spec/features/dev/new_spec.rb
- [ x] Commit messages clearly note what has been updated
- [x ] Tests are thorough (include Model tests where necessary) and are passing
- [x ] The Feature is working on my local server as expected
> User is created and can add developer role to BE user table

- app/services/developer_service.rb
- app/services/non_profit_service.rb
- app/services/representative_service.rb
- app/services/session_service.rb
env_url: http://localhost:3000
to your application.yml file
> feat: add env variable to deploy to heroku

- app/controllers/developers_controller.rb
- app/services/developer_service.rb
- app/views/developers/new.html.erb
Add ability to add LinkedIn and GitHub to dev profile
> post dev data to BE

- app/views/layouts/_nav.html.erb
- app/views/layouts/application.html.erb
- [ X] Commit messages clearly note what has been updated
- [X ] The Feature is working on my local server as expected
* Create logout, dashboard button for navbar
* Create session logic for button views on navbar 
* Create flash messages for errors
> Gf session logic

- app/views/non_profits/_new_project.html.erb
- app/views/non_profits/show.html.erb
- app/views/representatives/new.html.erb
> Clean Up Views and update for new api json format

- Gemfile
- app/controllers/developers_controller.rb
- app/controllers/projects_controller.rb
- app/facades/developer_facade.rb
- app/facades/project_facade.rb
- app/poros/project.rb
- app/poros/user.rb
- app/services/developer_service.rb
- app/services/project_service.rb
- app/views/developers/edit.html.erb
- app/views/developers/show.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/application.html.erb
- app/views/projects/show.html.erb
- config/routes.rb
- spec/features/dev/edit_spec.rb
- spec/features/dev/show_spec.rb
- spec/fixtures/developer_response.json
- spec/fixtures/project_response.json
- spec/rails_helper.rb
- spec/services/developer_service_spec.rb
- spec/spec_helper.rb
> Cb webmocks

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
> "Feat: add vcr gem, update gemfile lock

- app/services/non_profit_service.rb
- config/routes.rb
> Routes update

- app/controllers/calendars_controller.rb
- app/services/project_service.rb
- [ X] Commit messages clearly note what has been updated
- [ X] The Feature is working on my local server as expected
* Re-add lost calendar controller 
* Add lost create_project method in project service
> Local test

- app/controllers/developers_controller.rb
- app/services/developer_service.rb
- app/views/developers/edit.html.erb
- app/views/developers/show.html.erb
fixed edit button routing, user has to be updated on the backend
> Cb edit dev

- app/controllers/non_profits_controller.rb
- app/controllers/projects_controller.rb
- app/facades/project_facade.rb
- app/poros/project.rb
- app/services/project_service.rb
- app/views/projects/index.html.erb
- app/views/welcome/index.html.erb
- config/routes.rb
> Projects index

- app/controllers/developers_controller.rb
- app/facades/developer_facade.rb
- app/services/developer_service.rb
- app/views/developers/index.html.erb
- app/views/welcome/index.html.erb
- config/routes.rb
> Developer index

- app/views/developers/show.html.erb
> Feat: add link to project index from dev show page

- app/controllers/calendars_controller.rb
- app/services/calendly_service.rb
- app/views/non_profits/show.html.erb
- [ X] Commit messages clearly note what has been updated
- [ X] The Feature is working on my local server as expected
* Add calendly client secret to API call
> Gf calendly secret

- app/controllers/projects_controller.rb
- app/facades/project_facade.rb
- app/poros/project.rb
- app/poros/project_developer.rb
- app/services/project_service.rb
- app/views/projects/edit.html.erb
- app/views/projects/show.html.erb
- config/routes.rb
> project show page functionality

- app/controllers/projects_controller.rb
- app/views/projects/edit.html.erb
> add validations for project developers

- app/controllers/non_profits_controller.rb
- [X ] Commit messages clearly note what has been updated
- [X ] The Feature is working on my local server as expected
Refactor: remove line in nonprofit controller causing 404 error
> Refactor: nonprofit service causing 404 error

- app/controllers/non_profits_controller.rb
- [ X] Commit messages clearly note what has been updated
- [ X] The Feature is working on my local server as expected
* Recreate logic for nonprofit show controller
> Refactor: create logic for non profit show controller

- README.md
> Benistta patch 2
